# Generated by Django 6.0.5 on 2026-06-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_jobseeker_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='profile_pic',
            field=models.FileField(default='', upload_to='jobseeker/'),
        ),
    ]
