# Generated by Django 6.0.5 on 2026-06-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_jobseeker_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='profile_pic',
        ),
    ]
