# Generated by Django 6.0.5 on 2026-06-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_jobseeker_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='location',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='p_f',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='web',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
