# Generated by Django 6.0.5 on 2026-06-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_jobseeker_location_jobseeker_p_f_jobseeker_web'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='p_f',
            new_name='p_h',
        ),
    ]
