# Generated by Django 6.0.5 on 2026-06-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_p_f_jobseeker_p_h'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='about_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
