# Generated by Django 6.0.5 on 2026-06-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_jobseeker_about_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='Institute',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='degree',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='e_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='s_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
