# Generated by Django 6.0.5 on 2026-06-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_jobseeker_institute_jobseeker_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
