# Generated by Django 6.0.5 on 2026-06-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_jobseeker_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('500-1000', '500-1000'), ('1000+', '1000+')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_tagline',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cover_image',
            field=models.FileField(default='cover_image.png', upload_to='company/'),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='hq_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.FileField(default='logo.png', upload_to='company/'),
        ),
    ]
