# Generated by Django 6.0.5 on 2026-06-10 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='department_fk',
            field=models.ForeignKey(null=True,blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.departments'),
            preserve_default=False,
        ),
    ]
