# Generated by Django 6.0.5 on 2026-06-10 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_company_department_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry_type',
        ),
        migrations.AlterField(
            model_name='company',
            name='department_fk',
            field=models.ForeignKey(null=True,blank=True,on_delete=django.db.models.deletion.CASCADE, to='account.departments'),
        ),
    ]
