# Generated by Django 6.0.5 on 2026-06-10 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_company_industry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry_type',
            field=models.CharField(blank=True, choices=[('Software', 'Software'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Marketing', 'Marketing'), ('Education', 'Education'), ('other..', 'other..')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='department_fk',
            field=models.ForeignKey(blank=True,null=True, on_delete=django.db.models.deletion.CASCADE, to='account.departments'),
            preserve_default=False,
        ),
    ]
