# Generated by Django 6.0.5 on 2026-06-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_company_industry_type_alter_company_department_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='department_fk',
        ),
    ]
