# Generated by Django 6.0.5 on 2026-06-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_remove_company_department_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.PositiveIntegerField(default=123),
        ),
    ]
