# Generated by Django 6.0.5 on 2026-06-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_user_otp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="otp",
            new_name="OTP",
        ),
    ]
