# Generated by Django 6.0.5 on 2026-06-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_rename_otp_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseeker",
            name="percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=2, null=True
            ),
        ),
    ]
