# Generated by Django 6.0.5 on 2026-06-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_alter_jobseeker_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseeker",
            name="percentage",
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
    ]
