# Generated by Django 6.0.5 on 2026-07-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0022_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="fraind",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
