# Generated by Django 6.0.5 on 2026-07-08 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0023_chat_fraind"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Request", models.CharField(blank=True, max_length=20, null=True)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "jid_r_resever",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jid_r_resever",
                        to="account.jobseeker",
                    ),
                ),
                (
                    "jid_r_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jid_r_sender",
                        to="account.jobseeker",
                    ),
                ),
            ],
        ),
    ]
