# Generated by Django 6.0.5 on 2026-06-02 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('jobseeker', 'jobseeker'), ('company', 'company')], max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobseeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('number', models.PositiveIntegerField()),
                ('skills', models.CharField(max_length=50)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.user')),
            ],
        ),
    ]
