# Generated by Django 6.0.5 on 2026-06-02 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('website', models.CharField(max_length=50)),
                ('industry_type', models.CharField(choices=[('Software', 'Software'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Marketing', 'Marketing'), ('Education', 'Education')], max_length=20)),
                ('com_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.user')),
            ],
        ),
    ]
