# Generated by Django 6.0.5 on 2026-06-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='user_fk',
        ),
        migrations.DeleteModel(
            name='company',
        ),
        migrations.DeleteModel(
            name='jobseeker',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
