# Generated by Django 6.0.5 on 2026-06-12 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0017_remove_company_department_fk'),
        ('jobseeker', '0003_remove_jobseeker_user_fk_delete_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='resumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.PositiveIntegerField()),
                ('location', models.TextField()),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('pot_web', models.CharField(blank=True, max_length=50, null=True)),
                ('summary', models.TextField()),
                ('Institute', models.CharField(max_length=50)),
                ('p_year', models.PositiveIntegerField()),
                ('percentage', models.PositiveIntegerField()),
                ('job_tital', models.CharField(max_length=20)),
                ('w_company_name', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('skills', models.CharField(max_length=50)),
                ('Project_detail', models.TextField()),
                ('degree', models.CharField(max_length=50)),
                ('Language', models.CharField(max_length=50)),
                ('resume', models.FileField(blank=True, null=True, upload_to='jobseeker/resume/')),
                ('job_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.jobseeker')),
            ],
        ),
    ]
