# Generated by Django 6.0.5 on 2026-06-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumes',
            name='percentage',
            field=models.CharField(max_length=50),
        ),
    ]
