# Generated by Django 6.0.5 on 2026-06-14 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_company_department_fk'),
        ('jobseeker', '0006_alter_resumes_institute_alter_resumes_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tital', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='jobseeker/posts/')),
                ('job_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.jobseeker')),
            ],
        ),
    ]
