# Generated by Django 6.0.5 on 2026-06-15 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0007_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
