# Generated by Django 6.0.5 on 2026-06-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0008_posts_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='time',
            new_name='created_date',
        ),
    ]
