# Generated by Django 6.0.5 on 2026-06-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0009_rename_time_posts_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
