# Generated by Django 6.0.5 on 2026-06-15 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_company_department_fk'),
        ('company', '0004_alter_post_jobs_key_skils'),
        ('jobseeker', '0010_alter_posts_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statse', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('job_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.jobseeker')),
                ('jobs_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.post_jobs')),
                ('resume_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.resumes')),
            ],
        ),
    ]
