# Generated by Django 6.0.5 on 2026-06-18 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_remove_company_department_fk"),
        ("company", "0004_alter_post_jobs_key_skils"),
        ("jobseeker", "0011_apply"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.jobseeker",
                    ),
                ),
                (
                    "job_post_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.post_jobs",
                    ),
                ),
            ],
        ),
    ]
