# Generated by Django 6.0.5 on 2026-06-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobseeker", "0012_savedjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedjob",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Deactive", "Deactive")],
                default="Deactive",
                max_length=20,
            ),
        ),
    ]
