# Generated by Django 6.0.5 on 2026-06-20 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_alter_post_jobs_key_skils"),
        ("jobseeker", "0014_alter_savedjob_job_post_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedjob",
            name="job_post_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="company.post_jobs"
            ),
        ),
    ]
