# Generated by Django 6.0.5 on 2026-06-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobseeker", "0015_alter_savedjob_job_post_fk"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apply",
            old_name="statse",
            new_name="status",
        ),
    ]
