# Generated by Django 6.0.5 on 2026-07-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobseeker", "0016_rename_statse_apply_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="Interviewer_Name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="Schedule_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="apply",
            name="Schedule_time",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
