# Generated by Django 6.0.5 on 2026-06-10 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0017_remove_company_department_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('internship', 'internship')], max_length=20)),
                ('location', models.TextField()),
                ('min_salary', models.PositiveIntegerField()),
                ('max_salary', models.PositiveIntegerField()),
                ('experience', models.CharField(choices=[('Junior (1-3 yrs)', 'Junior (1-3 yrs)'), ('Mid-level (3-5 yrs)', 'Mid-level (3-5 yrs)'), ('Senior (5+ yrs)', 'Senior (5+ yrs)'), ('Lead / Architect (*+ yrs)', 'Lead / Architect (*+ yrs)')], max_length=30)),
                ('job_discription', models.TextField()),
                ('department_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.departments')),
            ],
        ),
    ]
