# Generated by Django 6.0.5 on 2026-06-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_jobs',
            name='key_skils',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
