# Generated by Django 6.0.5 on 2026-06-11 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_company_department_fk'),
        ('company', '0002_post_jobs_key_skils'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_jobs',
            name='company_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AlterField(
            model_name='post_jobs',
            name='experience',
            field=models.CharField(choices=[('Junior (1-3 yrs)', 'Junior (1-3 yrs)'), ('Mid-level (3-5 yrs)', 'Mid-level (3-5 yrs)'), ('Senior (5+ yrs)', 'Senior (5+ yrs)'), ('Lead / Architect (8+ yrs)', 'Lead / Architect (8+ yrs)')], max_length=30),
        ),
    ]
