# Generated by Django 6.0.5 on 2026-06-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_post_jobs_company_fk_alter_post_jobs_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_jobs',
            name='key_skils',
            field=models.TextField(),
        ),
    ]
