# Generated by Django 6.0.5 on 2026-06-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_alter_post_jobs_key_skils"),
    ]

    operations = [
        migrations.AddField(
            model_name="post_jobs",
            name="bookmark",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
