# Generated by Django 6.0.5 on 2026-06-21 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_alter_jobseeker_percentage"),
        ("company", "0005_post_jobs_bookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post_jobs",
            name="company_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.company"
            ),
        ),
    ]
