# Generated by Django 6.0.5 on 2026-06-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_alter_post_jobs_company_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post_jobs",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("Full-Time", "Full-Time"),
                    ("Part-Time", "Part-Time"),
                    ("Contract", "Contract"),
                    ("Internship", "Internship"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post_jobs",
            name="experience",
            field=models.CharField(
                choices=[
                    ("Fresher", "Fresher"),
                    ("Junior (1-3 yrs)", "Junior (1-3 yrs)"),
                    ("Mid-level (3-5 yrs)", "Mid-level (3-5 yrs)"),
                    ("Senior (5+ yrs)", "Senior (5+ yrs)"),
                    ("Lead / Architect (8+ yrs)", "Lead / Architect (8+ yrs)"),
                ],
                max_length=30,
            ),
        ),
    ]
