# Generated by Django 6.0.5 on 2026-06-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_alter_post_jobs_employment_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post_jobs",
            name="bookmark",
        ),
    ]
