# Generated by Django 6.0.5 on 2026-06-24 15:00

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_remove_post_jobs_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="post_jobs",
            name="post_time",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
